on: push
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: repo-sync
      uses: kingsd041/git-sync@ksd/v1.0
      env:
        SOURCE_REPO: "kingsd041/pandaria"
        DESTINATION_REPO: "kingsd041/pandaria-vip"
        BRANCH_NAME: "release/v2.2-ent release/v2.3-ent master"
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      with:
        args: $SOURCE_REPO $DESTINATION_REPO $BRANCH_NAME
